### ISSUE TITLE
Cannot use non-VISA instrument without PyVISA or FakeVISA set up

### ISSUE THREAD

**Issue by natezb** [mabuchilab/Instrumental#1]
You should be able to use a non-VISA instrument (e.g. an Attocube stage) even if VISA isn't configured properly.

Currently, importing anything from the drivers package forces FakeVISA to try to connect to a server, and if it doesn't find it, it will raise an exception.

**Comment by BernardoGO** [comment]
@natezb 
Have you fixed it?

**Comment by natezb** [comment]
I believe this has been mostly fixed for awhile. I just committed some finishing touches that make `list_instruments()` work correctly in this case.

Please reopen if the issue returns.
