### ISSUE TITLE
Dcx camera black level offset

### ISSUE THREAD

**Issue by horoshho** [mabuchilab/Instrumental#152]
Hi, is there a way to set up black level offset for camera via your package? I am using Thor Labs dcc1545m one. 
Regards

**Comment by natezb** [comment]
Yes, there is a `Facet` for this. It looks like the latest versions of docs have failed to build properly, but here are the [docs for version 0.5](https://instrumental-lib.readthedocs.io/en/0.5/uc480-cameras.html#instrumental.drivers.cameras.uc480.UC480_Camera.blacklevel_offset).
