### ISSUE TITLE
[non-issue] InstrumentKit

### ISSUE THREAD

**Issue by scasagrande** [mabuchilab/Instrumental#21]
Hello Instrumental devs,

I just wanted to take the time to bring a similar project to your attention, [InstrumentKit](https://www.github.com/Galvant/InstrumentKit), which I started several years ago with similar goals. While it looks like we had different priorities during initial development (for example, Instrumental relies on and integrates nicely with VISA, while InstrumentKit was designed to be connection agnostic without requiring VISA), there is considerable overlap between the two.

I hope that we can learn from each other so that we can continue to help the instrumentation community.

**Comment by natezb** [comment]
Hi Steven,

Thanks for your comments. If you're interested in investigating other python-based instrumentation software, check out [pyinstruments](https://github.com/pyinstruments/pyinstruments). It's a repo that links to the separate work that several groups have done.

Thanks,
Nate
