### ISSUE TITLE
Add more parameters to thorcam uc480 cameras

### ISSUE THREAD

**Issue by FMarazzi** [mabuchilab/Instrumental#22]
Besides the exposure, I also needed to change the gain. 
I have added this possiblity in a very quick and dirty way changing the constants.py and the uc480.py files.

**Comment by natezb** [comment]
The changes you've made look reasonable to me. When you're satisfied with it, issue a Pull Request and I can merge it in.

**Comment by FMarazzi** [comment]
I simply added "gain" as a keyword argument. I don't think I will need to add more parameters anytime soon. I did not have time to test the latest changes, but I don't see why they should not work.

If it is fine for you, I will issue the pull request.

**Comment by natezb** [comment]
Yep, go ahead with the PR.

**Comment by natezb** [comment]
Added by #23
