### ISSUE TITLE
Cannot set the integration time for CCS175 Thorlabs Spectrometer

### ISSUE THREAD

**Issue by hahaits** [mabuchilab/Instrumental#45]
![image](https://user-images.githubusercontent.com/34945537/34444020-09f9a59c-ec99-11e7-9fa7-4f1adb5d24af.png)

**Comment by natezb** [comment]
This means you should pass a `pint` `Quantity` (or a sting like `'50 ms'`) for the `integration_time`.

We should fix the docstring of `take_data()` to indicate this. We should also consider adding additional detail to the error message to make it less confusing for those unfamiliar with `pint`.

I'll keep this open until those items have been addressed, but please let me know if using units fixes your problem, or if you continue to have issues.

**Comment by hahaits** [comment]
Hi,

a string like '50 ms'

**Comment by natezb** [comment]
Hey, did you mean to say more than this? Or did you accidentally reply?

**Comment by hahaits** [comment]
Sorry, I meant to say, a string like ‘50 ms‘ worked, I used Pint as well but that didn’t work.

Hopefully the info comes in handy to make any changes to the library. If you do not remember, I had an issue with the integration time for Thorlabs CCS175.
