### ISSUE TITLE
CMOS Camera

### ISSUE THREAD

**Issue by berto10** [mabuchilab/Instrumental#65]
Hello, I'm trying to use the following thorlabs camera. https://www.thorlabs.com/thorproduct.cfm?partnumber=CS505CU 

However, when I try to look up the instrument nothing is showing up. Its working well for the other thorlabs camera but it does not work for this new camera. An suggesions on how to fix this issue?

![image](https://user-images.githubusercontent.com/37448045/47032751-19c1a280-d141-11e8-9e08-ee79f44b3259.png)

Thanks, 
Berto

**Comment by natezb** [comment]
Hey Berto,
That camera is in the Thorlabs "Compact Scientific" series, which uses a new library that we haven't yet wrapped. Check out #64 (#55) for the details. I'm closing this a a duplicate, but feel free to comment on one of those if you'd like.
