### ISSUE TITLE
Facet caching

### ISSUE THREAD

**Issue by jondoesntgit** [mabuchilab/Instrumental#73]
I’m writing a driver for the SR844 lock-in amplifier. I find that if I query it faster than .02s after I set a value, it produces an error. If I wait a little longer, no error.

Is there a way to have a cached value “expire” after a few seconds?

If this is not already implemented, don’t worry about it. I don’t expect to ever need to read back as fast as I’m writing during my test.

**Comment by natezb** [comment]
No, that's not something that's currently implemented.

**Comment by jondoesntgit** [comment]
Okay. Sounds good.
